export const JOB_SUB_TYPES = {
    'subjob_1': "Low voltage wiring",
    'subjob_2': "High voltage wiring",
    'subjob_3': "Conduit installation",
    'subjob_4': "Surface-mounted wiring",
    'subjob_5': "Flush-mounted wiring",
    'subjob_6': "Lighting circuit extension",
    'subjob_7': "Socket outlet installation",
    'subjob_8': "Switch installation",
    'subjob_9': "Distribution board upgrades",
    'subjob_10': "Circuit breaker replacement",
    'subjob_11': "RCD installation",
    'subjob_12': "Surge protection installation",
    'subjob_13': "Cable termination",
    'subjob_14': "Panel labeling",
    'subjob_15': "Control panel wiring",
    'subjob_16': "PLC programming",
    'subjob_17': "Motor starter wiring",
    'subjob_18': "Variable frequency drive setup",
    'subjob_19': "Soft starter installation",
    'subjob_20': "Emergency lighting setup",
    'subjob_21': "Exit sign installation",
    'subjob_22': "Smoke detector wiring",
    'subjob_23': "Heat detector wiring",
    'subjob_24': "Security alarm wiring",
    'subjob_25': "Access keypad installation",
    'subjob_26': "Network cable termination",
    'subjob_27': "Fiber optic splicing",
    'subjob_28': "Patch panel installation",
    'subjob_29': "Solar inverter wiring",
    'subjob_30': "Battery bank wiring",
    'subjob_31': "Generator ATS wiring",
    'subjob_32': "Busbar installation",
    'subjob_33': "Earthing rod installation",
    'subjob_34': "Lightning rod installation",
    'subjob_35': "Cable tray mounting",
    'subjob_36': "Trunking installation",
    'subjob_37': "Junction box wiring",
    'subjob_38': "Splicing and jointing",
    'subjob_39': "Temporary power distribution",
    'subjob_40': "Site lighting setup",
    'subjob_41': "Testing insulation resistance",
    'subjob_42': "Loop impedance testing",
    'subjob_43': "Earth continuity testing",
    'subjob_44': "Thermal imaging inspection",
    'subjob_45': "Load balancing",
    'subjob_46': "Energy meter installation",
    'subjob_47': "Remote monitoring setup",
    'subjob_48': "Smart relay programming",
    'subjob_49': "Time switch installation",
    'subjob_50': "Photocell sensor wiring",
    'subjob_51': "Occupancy sensor installation",
    'subjob_52': "HVAC control wiring",
    'subjob_53': "Compressor wiring",
    'subjob_54': "Pump control wiring",
    'subjob_55': "Elevator control panel wiring",
    'subjob_56': "Fire pump wiring",
    'subjob_57': "Transformer tap changing",
    'subjob_58': "Bus duct installation",
    'subjob_59': "Panel retrofitting",
    'subjob_60': "Cable fault location",
    'subjob_61': "Electrical documentation",
    'subjob_62': "Preventive maintenance",
    'subjob_63': "Corrective maintenance",
    'subjob_64': "Shutdown maintenance",
    'subjob_65': "Power quality analysis",
    'subjob_66': "Harmonic filtering",
    'subjob_67': "Capacitor bank installation",
    'subjob_68': "Lighting retrofit",
    'subjob_69': "LED conversion",
    'subjob_70': "Emergency generator hookup",
    'subjob_71': "Temporary generator connection",
    'subjob_72': "Load bank testing",
    'subjob_73': "Electrical risk assessment",
    'subjob_74': "Lockout/tagout implementation",
    'subjob_75': "Arc flash analysis",
    'subjob_76': "Electrical safety audit",
    'subjob_77': "Electrical system commissioning",
    'subjob_78': "System integration",
    'subjob_79': "Remote control setup",
    'subjob_80': "Wireless control installation",
    'subjob_81': "Building automation wiring",
    'subjob_82': "Data logger installation",
    'subjob_83': "SCADA wiring",
    'subjob_84': "Instrumentation wiring",
    'subjob_85': "Sensor calibration",
    'subjob_86': "Actuator wiring",
    'subjob_87': "Control cable laying",
    'subjob_88': "Cable gland installation",
    'subjob_89': "Cable tray earthing",
    'subjob_90': "Panel ventilation setup",
    'subjob_91': "Busbar trunking system",
    'subjob_92': "Distribution transformer wiring",
    'subjob_93': "Ring main unit wiring",
    'subjob_94': "Switchgear retrofitting",
    'subjob_95': "Meter panel wiring",
    'subjob_96': "Billing meter installation",
    'subjob_97': "Load shedding panel wiring",
    'subjob_98': "UPS bypass panel wiring",
    'subjob_99': "Battery charger wiring",
    'subjob_100': "DC system wiring",
    'subjob_101': "Solar combiner box wiring",
    'subjob_102': "String inverter wiring",
    'subjob_103': "Microinverter wiring",
    'subjob_104': "PV array wiring",
    'subjob_105': "Ground fault detection",
    'subjob_106': "Lightning surge counter installation",
  };
