export const JOB_TYPES = {
    'job_1': 'Quarrying',
    'job_2': 'Heavy industry',
    'job_3': 'Service calls',
    'job_4': 'Private customers',
    'job_5': 'Electrical infrastructure under renovation',
    'job_6': 'Light industry and offices',
    'job_7': 'Installation of accessories',
    'job_8': 'Installation of charging stations for electric vehicles',
    'job_9': 'Installation of decorative lighting fixtures',
    'job_10': 'Commands',
    'job_11': 'Controllers are programmed',
    'job_12': "Residential wiring",
    'job_13': "Commercial wiring",
    'job_14': "Industrial automation",
    'job_15': "Maintenance electrician",
    'job_16': "Panel assembly",
    'job_17': "Lighting installation",
    'job_18': "Fire alarm systems",
    'job_19': "Security systems installation",
    'job_20': "Solar panel installation",
    'job_21': "Generator installation",
    'job_22': "HVAC electrical work",
    'job_23': "Data and communication cabling",
    'job_24': "Smart home systems",
    'job_25': "Troubleshooting and diagnostics",
    'job_26': "Electrical inspection",
    'job_27': "Energy efficiency upgrades",
    'job_28': "Transformer installation",
    'job_29': "Substation maintenance",
    'job_30': "Cable tray installation",
    'job_31': "Overhead line work",
    'job_32': "Underground cable installation",
    'job_33': "Temporary site power",
    'job_34': "Emergency repairs",
    'job_35': "Testing and commissioning",
    'job_36': "Building management systems",
    'job_37': "Elevator electrical work",
    'job_38': "Motor control installation",
    'job_39': "Switchgear maintenance",
    'job_40': "Lighting control systems",
    'job_41': "UPS installation",
    'job_42': "Battery backup systems",
    'job_43': "Access control systems",
    'job_44': "Intercom installation",
    'job_45': "CCTV installation",
    'job_46': "Lightning protection systems",
    'job_47': "Earthing and bonding",
    'job_48': "Power factor correction",
    'job_49': "Electrical design and consulting",
    'job_50': "Project management",
    'job_51': "Site supervision",
    'job_52': "Electrical drafting",
    'job_53': "Estimating and quoting",
  };