export const LICENSES = {
    'license_1': 'Certified electrician',
    'license_2': 'Practical electrician',
    'license_3': 'Assistant electrician',
    'license_4': 'Electrician engineer',
    'license_5': 'Electrician technician',
    'license_6': 'Chief electrician',
    'license_7': 'Software developer',
    'license_8': 'Web designer',
    'license_9': 'Driver Training',
    'license_10': 'Court Reporter',
    'license_11': 'Cosmetology',
    'license_12': 'Plumber',
    'license_13': 'HVAC Technician',
    'license_14': 'Carpenter',
    'license_15': 'Welder',
    'license_16': 'Mason',
    'license_17': 'Painter',
    'license_18': 'Roofer',
    'license_19': 'Sheet Metal Worker',
    'license_20': 'Glazier',
    'license_21': 'Elevator Installer',
    'license_22': 'Boilermaker',
    'license_23': 'Crane Operator',
    'license_24': 'Heavy Equipment Operator',
    'license_25': 'Construction Manager',
    'license_26': 'Architect',
    'license_27': 'Civil Engineer',
    'license_28': 'Mechanical Engineer',
    'license_29': 'Structural Engineer',
    'license_30': 'Project Estimator',
    'license_31': 'Safety Officer',
    'license_32': 'Environmental Engineer',
    'license_33': 'Surveyor',
    'license_34': 'Geotechnical Engineer',
    'license_35': 'Urban Planner',
    'license_36': 'Interior Designer',
    'license_37': 'Landscape Architect',
    'license_38': 'Building Inspector',
    'license_39': 'Fire Protection Engineer',
    'license_40': 'Energy Auditor',
    'license_41': 'Solar Installer',
    'license_42': 'Wind Turbine Technician',
    'license_43': 'Power Plant Operator',
    'license_44': 'Substation Technician',
    'license_45': 'Lineworker',
    'license_46': 'Cable Splicer',
    'license_47': 'Telecommunications Technician',
    'license_48': 'Network Engineer',
    'license_49': 'IT Support Specialist',
    'license_50': 'Database Administrator',
    'license_51': 'Systems Analyst',
    'license_52': 'Cybersecurity Specialist',
    'license_53': 'Mobile App Developer',
    'license_54': 'Game Developer',
    'license_55': 'UI/UX Designer',
    'license_56': 'Graphic Designer',
    'license_57': 'Animator',
    'license_58': 'Video Editor',
    'license_59': 'Photographer',
    'license_60': 'Audio Engineer',
    'license_61': 'Broadcast Technician',
    'license_62': 'Journalist',
    'license_63': 'Copywriter',
    'license_64': 'Editor',
    'license_65': 'Translator',
    'license_66': 'Interpreter',
    'license_67': 'Teacher',
    'license_68': 'Professor',
    'license_69': 'Research Scientist',
    'license_70': 'Lab Technician',
    'license_71': 'Pharmacist',
    'license_72': 'Nurse',
    'license_73': 'Doctor',
    'license_74': 'Dentist',
    'license_75': 'Veterinarian',
    'license_76': 'Paramedic',
    'license_77': 'Physical Therapist',
    'license_78': 'Occupational Therapist',
    'license_79': 'Speech Therapist',
    'license_80': 'Psychologist',
    'license_81': 'Social Worker',
    'license_82': 'Counselor',
    'license_83': 'Lawyer',
    'license_84': 'Paralegal',
    'license_85': 'Judge',
    'license_86': 'Police Officer',
    'license_87': 'Firefighter',
    'license_88': 'Security Guard',
    'license_89': 'Private Investigator',
    'license_90': 'Pilot',
    'license_91': 'Flight Attendant',
    'license_92': 'Air Traffic Controller',
    'license_93': 'Aircraft Mechanic',
    'license_94': 'Ship Captain',
    'license_95': 'Marine Engineer',
    'license_96': 'Logistics Manager',
    'license_97': 'Supply Chain Analyst',
    'license_98': 'Warehouse Manager',
    'license_99': 'Truck Driver',
    'license_100': 'Forklift Operator',
  };