export const LIGHT_THEME = {
  backgroundColor: '#F0F0FA',
  tabBarBackground: '#0A62EA',
  tabBarTextColorActive: '#ffffff',
  tabBarTextColorInactive: '#ffffff80',
  textColor: '#000000',
  unactiveTextColor: '#999',
  defaultBlocksBackground: '#ffffff',
  defaultBlocksShadowColor: '#000',
  defaultBlocksMockBackground: '#D9D9D9',
  defaultBlocksMockColor: '#888',
  mainBadgeBackground: '#FE8A01',
  secondaryBadgeBackground: '#0A62EA',
  badgeTextColor: '#ffffff',
  formInputBackground: '#DFDFFF',
  formInputBackgroundEditMode: '#c5c5ff',
  formInputBorderColor: '#333',
  formInputLabelColor: '#333',
  formInputTextColor: '#555',
  formInputPlaceholderColor: '#888',
  buttonColorPrimaryDefault: '#0A62EA',
  buttonColorPrimaryHover: '#2F7DF2',
  buttonColorPrimaryActive: '#0854C4',
  buttonColorPrimaryDisabled: '#B3D0F5',
  buttonColorSecondaryDefault: '#FE8A01',
  buttonColorSecondaryHover: '#FF9F2A',
  buttonColorSecondaryActive: '#DC7600',
  buttonColorSecondaryDisabled: '#FEE0B3',
  buttonTextColorPrimary: '#ffffff',
  buttonTextColorSecondary: '#ffffff',
  primaryColor: '#0A62EA',
  secondaryColor: '#F0F0F0',
  accentColor: '#FF4081',
  borderColor: '#E0E0E0',
  profileDefaultBackground: '#0A62EA80',
  breakLineColor: '#0A62EA80',
  textColorSecondary: '#885588',
  switchTrackColor: '#DFDFFF',
  switchThumbColor: '#FE8A01',
  verifiedMarkerColor: '#44d15f',
  verifiedGradientEndColor: '#faec5d',
  topMarkerColor: '#ffaf40',
  topGradientEndColor: '#bff891',
  personalMarkerColor: '#C701FE',
  personalGradientEndColor: '#c629f2',
};

export const DARK_THEME = {
  
}