name: Build web and publish to gh-pages

on:
  push:
    branches: [ master ]   # оставил как у вас
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Verify assets path
        run: |
          ls -la assets || true
          ls -la assets/icon || true
          git ls-files | grep -i "assets/.*/email"
          
      - name: Build web (Expo export)
        # Для project pages: PUBLIC_URL="/<repo>/"
        # Для <user>.github.io замените на "/"
        run: |
          echo "PUBLIC_URL=/${{ github.event.repository.name }}/"
          PUBLIC_URL="/${{ github.event.repository.name }}/" npx expo export --platform web --output-dir dist

      - name: SPA fallback
        run: cp dist/index.html dist/404.html

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages
          commit_message: "ci: publish web"