name: Build web and publish to gh-pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build web (Expo export)
        # Для project pages (обычный репозиторий):
        # base-url должен быть /<repo>/ — оставляем динамически
        # Если репозиторий <user>.github.io — замените на: --base-url "/"
        run: npx expo export -p web --output-dir dist --base-url "/${{ github.event.repository.name }}/"

      - name: SPA fallback
        run: cp dist/index.html dist/404.html

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages
          commit_message: "ci: publish web"